version: '3'
services:
  backend:
    image: container
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - CURRENT_ENVIRONMENT=development
  frontend:
    image: frontend
    container_name: frontend
    ports:
    - 8080:80
    
